### PR TITLE
Remove is_{severely,enhanced}_disabled_for_ubi and add ESA_income as qualifying UBI disability

### PR DESCRIPTION
**Pull request by MaxGhenis**

### CODE REVIEW

**Comment by MaxGhenis** [comment]
The `ESA_income_reported` didn't work, got this error:
```
ValueError: You tried to compute the variable 'ESA_income_reported' for the entity 'people';
however the variable 'ESA_income_reported' is defined for 'benunits'.
```

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Works now after changing to `ESA_income_reported_personal`

Would like to add a test before merging though

**Comment by nikhilwoodruff** [comment]
Thanks @MaxGhenis - I've just added an example test for the disability flag, hopefully it's easy to follow. Right now the tests can be slightly difficult to specify when periods are different - for example, benefits defined on a per-week level are used to define yearly flags. It's not an issue for this, because the benefit receipt just needs to be positive, but if we were thresholding we'd need to specify the receipt in each week of the year. To solve this, I think we just need to use the ```set_input``` field that we haven't so far ([reference](https://openfisca.org/doc/coding-the-legislation/35_periods.html#automatically-process-variable-inputs-defined-for-periods-not-matching-the-definition-period)).

**Comment by MaxGhenis** [comment]
Oh cool thanks @nikhilwoodruff! Merging.

**Pull request merged**
